variable "network_id" {}
variable "subnet_id" {}
variable "nic_id" {}
variable "location" {}
variable "rgn"  {}
variable "vm_size" {}
variable "image_publisher" {}
variable "image_offer" {}
variable "image_sku" {}
variable "image_version" {}
variable "default_tags" {}
variable "admin_username" {}
variable "key_name" {}
