---

- name: Create devops group
  group:
    name: devops
    state: present

- name: Create devops users
  user:
    name: "{{ item }}"
    shell: "/bin/bash"
    groups: "devops"
    append: yes
  with_items: "{{ devops_users }}"

- name: Add public key for users
  authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', '{{ item }}') }}"
    state: present
  with_items: "{{ devops_users }}"



